### ISSUE TITLE
Converted color channels are reversed

### ISSUE THREAD

**Issue by Kettenhoax** [ros-sports/ros_image_to_qimage#20]
I tested the conversion-for-display feature added in commits up to aa02f2250d58ff84beca230adb4174568d5d024e, and when I visualize a BGR8 image, the channels are reversed.
It seems that the output encoding is left empty, see https://github.com/ros-sports/ros_image_to_qimage/blob/rolling/src/ros_image_to_qimage.cpp#L31
I believe the output encoding should be set to sensor_msgs::image_encodings::RGB8, since the rest of the method interprets the image as RGB8.

**Comment by ijnek** [comment]
@Kettenhoax thank you for trying out the new changes, and finding a bug!
I've confirmed that this is a bug, and have proposed a PR if you could review it? #21
